# Generated by Django 5.1 on 2024-09-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_name', models.CharField(max_length=200)),
                ('shope_name', models.CharField(max_length=200)),
                ('menu', models.FileField(upload_to='uploads/')),
                ('shope_no', models.IntegerField()),
                ('so_number', models.IntegerField()),
            ],
        ),
    ]
