# Generated by Django 5.1 on 2024-09-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fname', models.CharField(max_length=200)),
                ('c_lname', models.CharField(max_length=200)),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_phone', models.IntegerField()),
                ('c_adrs', models.TextField()),
                ('c_username', models.CharField(max_length=50)),
                ('c_pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
