# Generated by Django 5.1 on 2024-09-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_shopowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopOwner',
        ),
    ]
